DROP DATABASE IF EXISTS BoilerplateDB;

CREATE DATABASE BoilerplateDB;

USE BoilerplateDB;

CREATE TABLE Users(
	Id BINARY(16) PRIMARY KEY,
    Username VARCHAR(100) UNIQUE NOT NULL,
    `Password` VARCHAR(255) NOT NULL
);

CREATE TABLE Roles(
	Id BINARY(16) PRIMARY KEY,
	Authority VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE Users_Roles(
	User_Id BINARY(16)  NOT NULL,
    Role_Id BINARY(16)  NOT NULL,
    PRIMARY KEY(User_Id,Role_Id),
	FOREIGN KEY(User_Id) REFERENCES Users(Id),
	FOREIGN KEY(Role_Id) REFERENCES Roles(Id)
);